import assert from 'node:assert/strict';
import {ANY_RULE_VALUE,data,initialQuery,matches,queryProblem,ruleFamilyKeys,ruleFamilyValues,toRecordTransferCount} from './model';
const sample=data.samples.find(s=>s.rarity===4&&s.effects.some(e=>e.role==='恩宠'))!;
const grace=sample.effects.find(e=>e.role==='恩宠')!;
const q={...initialQuery(),effects:[],graces:[grace.id,'not-a-grace']};
assert.ok(matches(sample,q));
assert.ok(!matches(sample,{...q,graces:['not-a-grace']}));
const rules=[{id:'present',name:'present',keys:[sample.rules[0].key],variant:'any',mode:1},{id:'absent',name:'absent',keys:[-1],variant:'any',mode:1}];
assert.ok(matches(sample,{...q,rules}));
assert.ok(!matches(sample,{...q,rules:rules.map(r=>({...r,mode:0}))}));
assert.equal(queryProblem({...q,count:25}),'');
assert.ok(queryProblem({...q,count:26}));
assert.deepEqual(ruleFamilyValues('一难横行'),['50%','65%','80%']);
assert.equal(ruleFamilyKeys('一难横行',ANY_RULE_VALUE).length,69);
assert.equal(ruleFamilyKeys('一难横行','80%').length,23);
assert.equal(ruleFamilyKeys('造成的属性伤害增加','30%').length,4);
assert.equal(toRecordTransferCount(-1),0xFFFFFFFF);
console.log('7 query semantic checks passed');
