/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WorkerRequest =
  | {
      protocol: 1;
      id: string;
      method: "job.current";
      params: {};
    }
  | {
      protocol: 1;
      id: string;
      method: "handshake";
      params: {};
    }
  | {
      protocol: 1;
      id: string;
      method: "search.catalog";
      params: {
        playthrough: 3;
        rarity: 3 | 4 | 5;
        locale: "en-US" | "zh-CN" | "ja-JP";
      };
    }
  | {
      protocol: 1;
      id: string;
      method: "recommended_level.resolve";
      params: {
        displayed_level: number;
      };
    }
  | {
      protocol: 1;
      id: string;
      method: "search.start";
      params: {
        query: {
          playthrough: 3 | 4 | 5;
          rarity: 3 | 4 | 5;
          level: number;
          /**
           * @maxItems 32
           */
          primary_effect_ids: number[];
          /**
           * @maxItems 32
           */
          required_secondary_ids: number[];
          /**
           * @maxItems 8
           */
          required_secondary_id_groups:
            | []
            | [[number, ...number[]]]
            | [[number, ...number[]], [number, ...number[]]]
            | [[number, ...number[]], [number, ...number[]], [number, ...number[]]]
            | [[number, ...number[]], [number, ...number[]], [number, ...number[]], [number, ...number[]]]
            | [
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]]
              ]
            | [
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]]
              ]
            | [
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]]
              ]
            | [
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]],
                [number, ...number[]]
              ];
          grace_effect_id: number | null;
          /**
           * @maxItems 32
           */
          minimum_roll_percent_by_effect_id: [number, number][];
          auxiliary: {
            /**
             * @maxItems 32
             */
            required_terrain_effect_keys: number[];
            /**
             * @maxItems 8
             */
            required_terrain_effect_key_groups:
              | []
              | [[number, ...number[]]]
              | [[number, ...number[]], [number, ...number[]]]
              | [[number, ...number[]], [number, ...number[]], [number, ...number[]]]
              | [[number, ...number[]], [number, ...number[]], [number, ...number[]], [number, ...number[]]]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ];
            /**
             * @maxItems 32
             */
            required_special_rule_keys: number[];
            /**
             * @maxItems 8
             */
            required_special_rule_key_groups:
              | []
              | [[number, ...number[]]]
              | [[number, ...number[]], [number, ...number[]]]
              | [[number, ...number[]], [number, ...number[]], [number, ...number[]]]
              | [[number, ...number[]], [number, ...number[]], [number, ...number[]], [number, ...number[]]]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ];
            /**
             * @maxItems 32
             */
            required_enemy_lookup_keys: number[];
            /**
             * @maxItems 8
             */
            required_enemy_lookup_key_groups:
              | []
              | [[number, ...number[]]]
              | [[number, ...number[]], [number, ...number[]]]
              | [[number, ...number[]], [number, ...number[]], [number, ...number[]]]
              | [[number, ...number[]], [number, ...number[]], [number, ...number[]], [number, ...number[]]]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ]
              | [
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]],
                  [number, ...number[]]
                ];
          };
          /**
           * @maxItems 32
           */
          terrain_selection_ids?: string[];
          /**
           * Optional offline search filter on seed-derived initial capacity; empty accepts any. Does not edit the remaining byte.
           *
           * @maxItems 4
           */
          initial_challenge_counts?:
            [] | [number] | [number, number] | [number, number, number] | [number, number, number, number];
          /**
           * Optional OR set of final grace IDs, applied to completed candidates. Empty accepts any grace.
           *
           * @maxItems 64
           */
          grace_effect_ids?: number[];
          /**
           * @maxItems 24
           */
          effect_occurrences?: {
            scope: "primary" | "secondary" | "any";
            /**
             * @minItems 1
             * @maxItems 24
             */
            alternatives: [
              {
                effect_id: number;
                minimum_roll_percent: number;
              },
              ...{
                effect_id: number;
                minimum_roll_percent: number;
              }[]
            ];
          }[];
        };
        context_digest: string;
        result_count: number;
        page_trials: number;
        job_trials: number;
        allow_cpu_fallback: boolean;
        resume_token: string | null;
        cache_id?: string | null;
      };
    }
  | {
      protocol: 1;
      id: string;
      method: "job.snapshot";
      params: {
        job_id: string;
      };
    }
  | {
      protocol: 1;
      id: string;
      method: "job.cancel";
      params: {
        job_id: string;
      };
    }
  | {
      protocol: 1;
      id: string;
      method: "shutdown";
      params: {};
    }
  | {
      protocol: 1;
      id: string;
      method: "candidate.export";
      params: {
        job_id: string;
        candidate_id: string;
      };
    }
  | {
      protocol: 1;
      id: string;
      method: "cache.register";
      params: {
        cache_json: string;
      };
    }
  | {
      protocol: 1;
      id: string;
      method: "candidate.preview";
      params: {
        seed: number;
        rarity: 3 | 4 | 5;
        level: number;
      };
    };
