/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ProtectedResponse =
  | {
      protocol: 1;
      id: string | null;
      ok: true;
      result:
        | ProtectedJob
        | RuntimeStatus
        | LiveCharacter
        | EquipmentRules
        | EffectValues
        | MenuSelection
        | InventorySnapshot
        | LocalNameCatalog
        | ShutdownStatus
        | ProtectedHandshake
        | {
            job: ProtectedJob | null;
          }
        | {
            live_add: LiveAddOperation;
          }
        | {
            save_path: string;
          }
        | {
            live_batch: LiveBatch;
          }
        | {
            /**
             * @minItems 1
             * @maxItems 200
             */
            candidates: [CandidateTransfer, ...CandidateTransfer[]];
            save_path: string;
          }
        | {
            count_edit: CountEdit;
          }
        | {
            count_source: {
              save_path: string;
              source_sha256: string;
              record_hex: string;
            };
          };
    }
  | {
      protocol: 1;
      id: string | null;
      ok: false;
      error: {
        code: string;
        message: string;
      };
    };
export type EnemyStatePreviews = {
  solo: EnemyStatePreview;
  expedition: EnemyStatePreview;
} | null;

export interface ProtectedJob {
  job_id: string;
  kind:
    | "handshake"
    | "shutdown"
    | "job.snapshot"
    | "job.cancel"
    | "save.discover"
    | "save.register"
    | "save.inventory"
    | "save.audit_scrolls"
    | "save.prepare_edit"
    | "save.prepare_delete"
    | "save.prepare_install"
    | "save.backups"
    | "save.prepare_restore"
    | "save.template"
    | "save.discard"
    | "save.commit"
    | "save.operation"
    | "runtime.status"
    | "runtime.stop_override"
    | "runtime.start_override"
    | "runtime.generate"
    | "runtime.export"
    | "runtime.search"
    | "runtime.capture_grace"
    | "save.cached_grace"
    | "save.operations"
    | "save.live_add_source"
    | "runtime.live_add_prepare"
    | "runtime.live_add_execute"
    | "runtime.live_add_status"
    | "runtime.live_add_recover"
    | "runtime.live_add_cancel"
    | "save.prepare_install_many"
    | "save.materialize_live_many"
    | "runtime.live_batch_prepare"
    | "runtime.live_batch_execute"
    | "runtime.live_batch_status"
    | "runtime.live_batch_cancel"
    | "save.recycle_backups"
    | "save.backup_location"
    | "save.data_directory"
    | "save.auxiliary_preview"
    | "save.count_edit_source"
    | "runtime.count_prepare"
    | "runtime.count_execute"
    | "runtime.count_status"
    | "runtime.count_recover"
    | "save.character"
    | "save.prepare_character_edit"
    | "runtime.character_edit";
  state: "running" | "cancel_requested" | "completed" | "failed";
  sequence: number;
  cancellable: boolean;
  progress: {
    [k: string]: unknown;
  } | null;
  result:
    | LiveCharacterEdit
    | SaveCharacter
    | RuntimeStatus
    | SaveReference
    | SaveInventory
    | ScrollAudit
    | SavePlan
    | OperationReceipt
    | CandidateTransfer
    | {
        saves: SaveReference[];
      }
    | {
        discarded: boolean;
      }
    | {
        template_hex: string;
        source_sha256: string;
        context_digest: string;
        save_fingerprint: string;
      }
    | {
        candidate: {
          candidate_id: string;
          context_digest: string;
          seed: number;
          playthrough: number | null;
          rarity: number;
          record_stage: "final_record" | "native_stage_one" | "effect_sequence_only";
          installable: boolean;
          install_blocker: string | null;
          effects: {
            slot: number;
            effect_id: number;
            value: number;
            metadata: number;
            prefix: number;
            tail_0: number;
            tail_1: number;
            roll_percent: number | null;
          }[];
          auxiliary: {
            terrain: {
              value: number;
              display_effect_keys: number[];
            };
            enemy_groups: {
              lookup_key: number;
              role: number;
            }[][];
            special_rules: {
              key: number;
              raw_value: number | null;
              display_value: number | null;
              display_unit: string | null;
              display_grade: string | null;
              qualifier_kind: string | null;
              qualifier_key: number | null;
            }[];
          } | null;
          enemy_states: EnemyStatePreviews;
          cursor: number | null;
          evidence: "certified_offline_replay" | "native_finalized_generation";
          installation_available: boolean;
          initial_challenge_capacity: number;
        } | null;
        resume_trial?: number | null;
        resume_seed?: number;
      }
    | {
        backups: {
          backup_id: string;
          timestamp: string;
          action: string;
          manifest_schema: string;
          file_count: number;
        }[];
      }
    | null
    | {
        cache_json: string;
      }
    | {
        captured: true;
        playthrough: number;
        rarity: number;
      }
    | {
        operations: OperationReceipt[];
      }
    | {
        live_add: LiveAddOperation;
      }
    | {
        save_path: string;
      }
    | {
        live_batch: LiveBatch;
      }
    | {
        /**
         * @minItems 1
         * @maxItems 200
         */
        candidates: [CandidateTransfer, ...CandidateTransfer[]];
        save_path: string;
      }
    | {
        backup_directory: string;
      }
    | {
        data_directory: string;
        restart_required: boolean;
      }
    | {
        auxiliary_json: string;
      }
    | {
        count_edit: CountEdit;
      }
    | {
        count_source: {
          save_path: string;
          source_sha256: string;
          record_hex: string;
        };
      };
  error: {
    code: string;
    message: string;
  } | null;
}
export interface LiveCharacterEdit {
  character_edit: {
    state: "verified" | "rejected" | "uncertain";
    process_id: number;
    currencies: {
      [k: string]: unknown;
    }[];
    equipment: {
      [k: string]: unknown;
    }[];
    items?: {
      [k: string]: unknown;
    }[];
    error: string | null;
  };
}
export interface SaveCharacter {
  save_id: string;
  source_sha256: string;
  currencies: CharacterCurrencies;
  equipment_slots: number;
  /**
   * @maxItems 2500
   */
  equipment: CharacterEquipment[];
  items?: CharacterItem[] | null;
}
export interface CharacterCurrencies {
  amrita: number | null;
  gold: number | null;
}
export interface CharacterEquipment {
  slot_index: number;
  item_id: number;
  appearance_id: number;
  quantity: number;
  level: number;
  level_before_forge: number;
  plus: number;
  familiarity: number;
  inventory_key: number;
  seed: number;
  rarity: number;
  type_class?: number | null;
  /**
   * @maxItems 7
   */
  effects:
    | []
    | [CharacterEquipmentEffect]
    | [CharacterEquipmentEffect, CharacterEquipmentEffect]
    | [CharacterEquipmentEffect, CharacterEquipmentEffect, CharacterEquipmentEffect]
    | [CharacterEquipmentEffect, CharacterEquipmentEffect, CharacterEquipmentEffect, CharacterEquipmentEffect]
    | [
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect
      ]
    | [
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect
      ]
    | [
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect,
        CharacterEquipmentEffect
      ];
  record_sha256?: string;
  hell?: boolean;
  hell_skill?: number;
  audit?: {
    verdict?: "natural" | "unverified" | "unnatural";
    natural: boolean;
    /**
     * @maxItems 64
     */
    findings: {
      code: string;
      slot?: number;
      other?: number;
      expected?: number;
      actual?: number;
    }[];
    /**
     * @maxItems 64
     */
    unverified?: {
      code: string;
      slot?: number;
      other?: number;
      expected?: number;
      actual?: number;
    }[];
  } | null;
}
export interface CharacterEquipmentEffect {
  index: number;
  effect_id: number;
  value: number;
}
export interface CharacterItem {
  container: "held" | "storage";
  slot_index: number;
  item_id: number;
  quantity: number | null;
  limit: number;
  record_sha256: string;
}
export interface RuntimeStatus {
  override_state: "stopped" | "armed_no_hit" | "applied_hit" | "unknown";
  hit_count: number;
  pending_remote_calls: number;
  safe_to_shutdown: boolean;
  error: string | null;
}
export interface SaveReference {
  save_id: string;
  path: string;
  account_id: string;
  save_slot: number;
}
export interface SaveInventory {
  save_id: string;
  snapshot_id: string;
  source_sha256: string;
  account_id: string;
  empty_slots: number;
  entries: {
    slot_index: number;
    header: {
      playthrough: number;
      level: number;
      recommended_level: number;
      seed: number;
      rarity: 3 | 4 | 5;
      transfer_count: number;
    };
    /**
     * @minItems 7
     * @maxItems 7
     */
    effects: [
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      }
    ];
    derived: {
      initial_challenge_capacity: number;
      remaining_challenge_attempts: number;
      recommended_displayed_level: number;
      recommended_raw_was_clamped: boolean;
      recommended_raw_level?: number;
    };
  }[];
}
export interface ScrollAudit {
  save_id: string;
  snapshot_id: string;
  source_sha256: string;
  status: "proven_reachable" | "proven_rule_violation" | "no_violation_found_unproven" | "insufficient_data";
  coverage_scope: "generated_effect_projection";
  context: AuditContextProof;
  /**
   * @maxItems 400
   */
  rows: ScrollAuditRow[];
}
export interface AuditContextProof {
  product_version: string;
  game_profile: string;
  game_file_version: string | null;
  versioned_resource_dir: string | null;
  bundle_digest: string | null;
  versioned_digest: string | null;
  resources_digest: string;
  algorithm_version: string;
  policy_version: string;
  context_digest: string;
  legacy_context_digest: string | null;
  production_authority: boolean;
  seed_accelerator_abi: number | null;
  seed_accelerator_build_id: string | null;
}
export interface ScrollAuditRow {
  slot_index: number;
  record_offset: number;
  record_sha256: string;
  record_type: number;
  playthrough: number | null;
  seed: number;
  level: number;
  rarity: number;
  coverage_scope: "generated_effect_projection";
  status: "proven_reachable" | "proven_rule_violation" | "no_violation_found_unproven" | "insufficient_data";
  /**
   * @maxItems 32
   */
  reasons: string[];
  replay_evidence: AuditReplayEvidence;
}
export interface AuditReplayEvidence {
  attempted: boolean;
  matched: boolean;
  matched_phase: ("R3" | "stage_one" | "final") | null;
  /**
   * @maxItems 32
   */
  compared_fields: string[];
  /**
   * @maxItems 32
   */
  ignored_fields: string[];
  observed_projection: AuditProjection | null;
  /**
   * @maxItems 2
   */
  phase_results: [] | [AuditPhaseResult] | [AuditPhaseResult, AuditPhaseResult];
}
export interface AuditProjection {
  record_type: number;
  playthrough: number;
  seed: number;
  level: number;
  rarity: number;
  /**
   * @minItems 7
   * @maxItems 7
   */
  effects: [
    AuditEffectProjection,
    AuditEffectProjection,
    AuditEffectProjection,
    AuditEffectProjection,
    AuditEffectProjection,
    AuditEffectProjection,
    AuditEffectProjection
  ];
}
export interface AuditEffectProjection {
  slot_index: number;
  prefix: number;
  effect_id: number;
  value: number;
  metadata: number;
  tail_0: number;
  tail_1: number;
}
export interface AuditPhaseResult {
  phase: "R3" | "stage_one" | "final";
  matched: boolean;
  expected_projection: AuditProjection | null;
  /**
   * @maxItems 32
   */
  mismatches: string[];
}
export interface SavePlan {
  plan_id: string;
  save_id: string;
  kind: "edit" | "delete" | "install" | "restore" | "install_many";
  source_sha256: string;
  expires_in_seconds: number;
  preview: {
    [k: string]: unknown;
  };
}
export interface OperationReceipt {
  operation_id: string;
  commit_status: "executing" | "committed" | "committed_with_warning" | "not_committed" | "unknown";
  warning: string | null;
  details: {
    [k: string]: unknown;
  };
  save_id?: string;
}
export interface CandidateTransfer {
  candidate_id: string;
  context_digest: string;
  level: number;
  seed: number;
  playthrough: number;
  rarity: 3 | 4 | 5;
  record_stage: "final_record" | "native_stage_one" | "effect_sequence_only";
  record_hex: string;
  installation_record_hex: string | null;
  /**
   * @minItems 1
   * @maxItems 7
   */
  effects:
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ];
}
export interface EnemyStatePreview {
  seed: number;
  playthrough: number;
  variant: "solo" | "expedition";
  terrain: number | null;
  /**
   * @maxItems 64
   */
  occurrences: {
    wave_index: number;
    position: number;
    lookup_key: number;
    role: number;
    source_row_index: number;
    availability: "base" | "expedition_only";
    native_spawn_key: number;
    possessed: "yes" | "no" | "unknown";
    curse: "guaranteed" | "possible" | "never" | "unknown";
    curse_probability: number | null;
    curse_if_fresh_null_source_selector_runs: "guaranteed" | "never" | "unknown";
    evidence_grade: string;
    curse_evidence: string;
  }[];
  possessed_complete: boolean;
  /**
   * @maxItems 64
   */
  missing_inputs: string[];
  curse_scope: string;
  curse_count_range: [number, number] | null;
  curse_count_domain: string | null;
}
export interface LiveAddOperation {
  operation_id: string;
  plan_digest: string;
  state: "prepared" | "cancelled" | "uncertain" | "verified" | "rejected_before_dispatch";
  can_dispatch: boolean;
  can_cancel: boolean;
  receipt: null | {
    [k: string]: unknown;
  };
  seed?: number;
  rarity?: 3 | 4 | 5;
  count_before?: number;
  backup_path?: string;
  instance_serial?: string;
  persistence?: "requires_normal_game_save";
}
export interface LiveBatch {
  batch_id: string;
  plan_digest: string;
  state: "prepared" | "complete" | "partial" | "uncertain" | "cancelled";
  count: number;
  verified_count: number;
  /**
   * @maxItems 200
   */
  child_operation_ids: string[];
}
export interface CountEdit {
  operation_id: string;
  plan_digest: string;
  state: "prepared" | "verified" | "rejected" | "uncertain";
  seed: number;
  rarity: number;
  old_count: number;
  new_count: number;
  error: string | null;
}
export interface LiveCharacter {
  source: "runtime";
  game_version: string;
  process_id: number;
  currencies: CharacterCurrencies;
  equipment_slots: number;
  /**
   * @maxItems 2500
   */
  equipment: CharacterEquipment[];
  items?: CharacterItem[] | null;
}
export interface EquipmentRules {
  item_id: number;
  known: boolean;
  rarity?: number;
  level?: number;
  hell?: boolean;
  hell_capable?: boolean;
  roles?:
    | []
    | ["innate" | "hell" | "random" | "set" | "grace"]
    | ["innate" | "hell" | "random" | "set" | "grace", "innate" | "hell" | "random" | "set" | "grace"]
    | [
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace"
      ]
    | [
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace"
      ]
    | [
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace"
      ]
    | [
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace"
      ]
    | [
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace",
        "innate" | "hell" | "random" | "set" | "grace"
      ]
    | null;
  /**
   * @maxItems 4096
   */
  innate?: number[];
  set_effect?: number | null;
  /**
   * @maxItems 4096
   */
  graces?: number[];
  /**
   * @maxItems 4096
   */
  random_pool?: {
    effect_id: number;
    star: boolean;
    min?: number;
    max?: number;
  }[];
  /**
   * @maxItems 4096
   */
  hell_pool?: {
    effect_id: number;
    star: boolean;
    min?: number;
    max?: number;
  }[];
  /**
   * @maxItems 4096
   */
  hell_skills?: number[];
}
export interface EffectValues {
  effect_id: number;
  rarity: number;
  level: number;
  star: boolean | null;
  /**
   * @maxItems 256
   */
  values: {
    value: number;
    roll_min: number;
    roll_max: number;
    probability: number;
    top_fraction: number;
  }[];
}
export interface MenuSelection {
  process_id: number;
  menu_open: boolean;
  slot_index?: number | null;
  container?: "equipment" | "held" | "storage";
  item_id?: number;
}
export interface InventorySnapshot {
  status: "observed";
  game_version: "2.0.2.0";
  observed_at: string;
  process: {
    pid: number;
    creation_filetime: string;
  };
  start: number;
  limit: number;
  observed_slot_count: number;
  next_start: number | null;
  /**
   * @maxItems 64
   */
  rows: InventorySnapshotRow[];
  consistency: "reread_equal";
  read_only: true;
}
export interface InventorySnapshotRow {
  slot: number;
  item_id: number;
  level_raw: number;
  plus_raw: number;
  quantity_raw: number;
  rarity_raw: number;
  record_sha256: string;
  /**
   * @minItems 7
   * @maxItems 7
   */
  effects: [
    {
      slot: number;
      id: number;
      raw_value: number;
    },
    {
      slot: number;
      id: number;
      raw_value: number;
    },
    {
      slot: number;
      id: number;
      raw_value: number;
    },
    {
      slot: number;
      id: number;
      raw_value: number;
    },
    {
      slot: number;
      id: number;
      raw_value: number;
    },
    {
      slot: number;
      id: number;
      raw_value: number;
    },
    {
      slot: number;
      id: number;
      raw_value: number;
    }
  ];
}
export interface LocalNameCatalog {
  schema: "nioh3-local-name-catalog-v1";
  status: "ok";
  source: LocalNameCatalogSource;
  /**
   * @maxItems 10000
   */
  rows: LocalNameCatalogRow[];
  counts: LocalNameCatalogCounts;
  /**
   * @maxItems 128
   */
  warnings: string[];
  /**
   * @maxItems 10000
   */
  conflicts: LocalNameCatalogConflict[];
  claim_boundary: string;
}
export interface LocalNameCatalogSource {
  role: "save_active_items" | "ct_equipment" | "trainer_equipment";
  namespace: "save_item_u16_le_bytes" | "ct_raw_bytes" | "trainer_numeric";
  source_label: string;
  declared_version: string;
  locale: "zh-CN" | "en-US" | "ja-JP";
  bytes: number;
  sha256: string;
}
export interface LocalNameCatalogRow {
  input_index: number;
  row_index: number;
  source_role: "save_active_items" | "ct_equipment" | "trainer_equipment";
  namespace: "save_item_u16_le_bytes" | "ct_raw_bytes" | "trainer_numeric";
  raw_key: string;
  key_bytes_hex: string;
  id: number | null;
  display_id: number | null;
  high_word: number | null;
  name: string | null;
  state: "accepted" | "sentinel_zero" | "sentinel_all_ones" | "unparsable_key" | "unsupported_width" | "out_of_range";
  quarantine_reason: string | null;
  displayable: boolean;
}
export interface LocalNameCatalogCounts {
  input_rows: number;
  accepted_rows: number;
  display_rows: number;
  sentinel_rows: number;
  quarantined_rows: number;
  conflict_rows: number;
  conflict_ids: number;
}
export interface LocalNameCatalogConflict {
  id: number;
  namespace: "save_item_u16_le_bytes" | "ct_raw_bytes" | "trainer_numeric";
  /**
   * @minItems 2
   * @maxItems 10000
   */
  names: [string, string, ...string[]];
  /**
   * @minItems 2
   * @maxItems 10000
   */
  row_indices: [number, number, ...number[]];
}
export interface ShutdownStatus {
  safe_to_shutdown: boolean;
  error?: string | null;
}
export interface ProtectedHandshake {
  role: "save" | "runtime";
  protocol: 1;
  contract_digest: string;
  context: {
    product_version: string;
    game_profile: string;
    resources_digest: string;
    algorithm_version: string;
    policy_version: string;
    context_digest: string;
    seed_accelerator_abi: number | null;
    seed_accelerator_build_id: string | null;
  };
  kill_safe: false;
}
