/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ProtectedResponse =
  | {
      protocol: 1;
      id: string | null;
      ok: true;
      result:
        | ProtectedJob
        | RuntimeStatus
        | ShutdownStatus
        | ProtectedHandshake
        | {
            job: ProtectedJob | null;
          }
        | {
            live_add: LiveAddOperation;
          }
        | {
            save_path: string;
          }
        | {
            live_batch: LiveBatch;
          }
        | {
            /**
             * @minItems 1
             * @maxItems 200
             */
            candidates: [CandidateTransfer, ...CandidateTransfer[]];
            save_path: string;
          }
        | {
            count_edit: CountEdit;
          }
        | {
            count_source: {
              save_path: string;
              source_sha256: string;
              record_hex: string;
            };
          };
    }
  | {
      protocol: 1;
      id: string | null;
      ok: false;
      error: {
        code: string;
        message: string;
      };
    };

export interface ProtectedJob {
  job_id: string;
  kind:
    | "handshake"
    | "shutdown"
    | "job.snapshot"
    | "job.cancel"
    | "save.discover"
    | "save.register"
    | "save.inventory"
    | "save.prepare_edit"
    | "save.prepare_delete"
    | "save.prepare_install"
    | "save.backups"
    | "save.prepare_restore"
    | "save.template"
    | "save.discard"
    | "save.commit"
    | "save.operation"
    | "runtime.status"
    | "runtime.stop_override"
    | "runtime.start_override"
    | "runtime.generate"
    | "runtime.export"
    | "runtime.search"
    | "runtime.capture_grace"
    | "save.cached_grace"
    | "save.operations"
    | "save.live_add_source"
    | "runtime.live_add_prepare"
    | "runtime.live_add_execute"
    | "runtime.live_add_status"
    | "runtime.live_add_recover"
    | "runtime.live_add_cancel"
    | "save.prepare_install_many"
    | "save.materialize_live_many"
    | "runtime.live_batch_prepare"
    | "runtime.live_batch_execute"
    | "runtime.live_batch_status"
    | "runtime.live_batch_cancel"
    | "save.recycle_backups"
    | "save.backup_location"
    | "save.data_directory"
    | "save.auxiliary_preview"
    | "save.count_edit_source"
    | "runtime.count_prepare"
    | "runtime.count_execute"
    | "runtime.count_status"
    | "runtime.count_recover";
  state: "running" | "cancel_requested" | "completed" | "failed";
  sequence: number;
  cancellable: boolean;
  progress: {
    [k: string]: unknown;
  } | null;
  result:
    | RuntimeStatus
    | SaveReference
    | SaveInventory
    | SavePlan
    | OperationReceipt
    | CandidateTransfer
    | {
        saves: SaveReference[];
      }
    | {
        discarded: boolean;
      }
    | {
        template_hex: string;
        source_sha256: string;
        context_digest: string;
        save_fingerprint: string;
      }
    | {
        candidate: {
          candidate_id: string;
          context_digest: string;
          seed: number;
          playthrough: number | null;
          rarity: number;
          record_stage: "final_record" | "native_stage_one" | "effect_sequence_only";
          installable: boolean;
          install_blocker: string | null;
          effects: {
            slot: number;
            effect_id: number;
            value: number;
            metadata: number;
            prefix: number;
            tail_0: number;
            tail_1: number;
            roll_percent: number | null;
          }[];
          auxiliary: {
            terrain: {
              value: number;
              display_effect_keys: number[];
            };
            enemy_groups: {
              lookup_key: number;
              role: number;
            }[][];
            special_rules: {
              key: number;
              raw_value: number | null;
              display_value: number | null;
              display_unit: string | null;
              display_grade: string | null;
              qualifier_kind: string | null;
              qualifier_key: number | null;
            }[];
          } | null;
          cursor: number | null;
          evidence: "certified_offline_replay" | "native_finalized_generation";
          installation_available: boolean;
          initial_challenge_capacity: number;
        } | null;
        resume_trial?: number | null;
        resume_seed?: number;
      }
    | {
        backups: {
          backup_id: string;
          timestamp: string;
          action: string;
          manifest_schema: string;
          file_count: number;
        }[];
      }
    | null
    | {
        cache_json: string;
      }
    | {
        captured: true;
        playthrough: number;
        rarity: number;
      }
    | {
        operations: OperationReceipt[];
      }
    | {
        live_add: LiveAddOperation;
      }
    | {
        save_path: string;
      }
    | {
        live_batch: LiveBatch;
      }
    | {
        /**
         * @minItems 1
         * @maxItems 200
         */
        candidates: [CandidateTransfer, ...CandidateTransfer[]];
        save_path: string;
      }
    | {
        backup_directory: string;
      }
    | {
        data_directory: string;
        restart_required: boolean;
      }
    | {
        auxiliary_json: string;
      }
    | {
        count_edit: CountEdit;
      }
    | {
        count_source: {
          save_path: string;
          source_sha256: string;
          record_hex: string;
        };
      };
  error: {
    code: string;
    message: string;
  } | null;
}
export interface RuntimeStatus {
  override_state: "stopped" | "armed_no_hit" | "applied_hit" | "unknown";
  hit_count: number;
  pending_remote_calls: number;
  safe_to_shutdown: boolean;
  error: string | null;
}
export interface SaveReference {
  save_id: string;
  path: string;
  account_id: string;
  save_slot: number;
}
export interface SaveInventory {
  save_id: string;
  snapshot_id: string;
  source_sha256: string;
  account_id: string;
  empty_slots: number;
  entries: {
    slot_index: number;
    header: {
      playthrough: number;
      level: number;
      recommended_level: number;
      seed: number;
      rarity: 3 | 4 | 5;
      transfer_count: number;
    };
    /**
     * @minItems 7
     * @maxItems 7
     */
    effects: [
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      },
      {
        slot_index: number;
        effect_id: number;
        value: number;
        prefix: number;
        metadata: number;
        tail_0: number;
        tail_1: number;
      }
    ];
    derived: {
      initial_challenge_capacity: number;
      remaining_challenge_attempts: number;
      recommended_displayed_level: number;
      recommended_raw_was_clamped: boolean;
    };
  }[];
}
export interface SavePlan {
  plan_id: string;
  save_id: string;
  kind: "edit" | "delete" | "install" | "restore" | "install_many";
  source_sha256: string;
  expires_in_seconds: number;
  preview: {
    [k: string]: unknown;
  };
}
export interface OperationReceipt {
  operation_id: string;
  commit_status: "executing" | "committed" | "committed_with_warning" | "not_committed" | "unknown";
  warning: string | null;
  details: {
    [k: string]: unknown;
  };
  save_id?: string;
}
export interface CandidateTransfer {
  candidate_id: string;
  context_digest: string;
  level: number;
  seed: number;
  playthrough: number;
  rarity: 3 | 4 | 5;
  record_stage: "final_record" | "native_stage_one" | "effect_sequence_only";
  record_hex: string;
  installation_record_hex: string | null;
  /**
   * @minItems 1
   * @maxItems 7
   */
  effects:
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ];
}
export interface LiveAddOperation {
  operation_id: string;
  plan_digest: string;
  state: "prepared" | "cancelled" | "uncertain" | "verified" | "rejected_before_dispatch";
  can_dispatch: boolean;
  can_cancel: boolean;
  receipt: null | {
    [k: string]: unknown;
  };
  seed?: number;
  rarity?: 3 | 4 | 5;
  count_before?: number;
  backup_path?: string;
  instance_serial?: string;
  persistence?: "requires_normal_game_save";
}
export interface LiveBatch {
  batch_id: string;
  plan_digest: string;
  state: "prepared" | "complete" | "partial" | "uncertain" | "cancelled";
  count: number;
  verified_count: number;
  /**
   * @maxItems 200
   */
  child_operation_ids: string[];
}
export interface CountEdit {
  operation_id: string;
  plan_digest: string;
  state: "prepared" | "verified" | "rejected" | "uncertain";
  seed: number;
  rarity: number;
  old_count: number;
  new_count: number;
  error: string | null;
}
export interface ShutdownStatus {
  safe_to_shutdown: boolean;
  error?: string | null;
}
export interface ProtectedHandshake {
  role: "save" | "runtime";
  protocol: 1;
  contract_digest: string;
  context: {
    product_version: string;
    game_profile: string;
    resources_digest: string;
    algorithm_version: string;
    policy_version: string;
    context_digest: string;
    seed_accelerator_abi: number | null;
    seed_accelerator_build_id: string | null;
  };
  kill_safe: false;
}
