/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WorkerResponse =
  | {
      protocol: 1;
      id: string | null;
      ok: true;
      result:
        | JobSnapshot
        | Handshake
        | {
            stopped: true;
          }
        | SearchCatalog
        | CandidateTransfer
        | CacheReference
        | RecommendedLevelResolution
        | {
            job: JobSnapshot | null;
          }
        | {
            candidate: {
              candidate_id: string;
              context_digest: string;
              seed: number;
              playthrough: number | null;
              rarity: number;
              record_stage: "final_record" | "native_stage_one" | "effect_sequence_only";
              installable: boolean;
              install_blocker: string | null;
              effects: {
                slot: number;
                effect_id: number;
                value: number;
                metadata: number;
                prefix: number;
                tail_0: number;
                tail_1: number;
                roll_percent: number | null;
              }[];
              auxiliary: {
                terrain: {
                  value: number;
                  display_effect_keys: number[];
                };
                enemy_groups: {
                  lookup_key: number;
                  role: number;
                }[][];
                special_rules: {
                  key: number;
                  raw_value: number | null;
                  display_value: number | null;
                  display_unit: string | null;
                  display_grade: string | null;
                  qualifier_kind: string | null;
                  qualifier_key: number | null;
                }[];
              } | null;
              cursor: number | null;
              evidence: "certified_offline_replay" | "native_finalized_generation";
              installation_available: boolean;
              initial_challenge_capacity: number;
            };
            transfer: CandidateTransfer;
          };
    }
  | {
      protocol: 1;
      id: string | null;
      ok: false;
      error: {
        code: string;
        message: string;
      };
    };
export type RecommendedLevelResolution =
  | {
      requested_displayed_level: number;
      status: "exact";
      /**
       * @minItems 1
       * @maxItems 1245
       */
      canonical_internal_levels: [number, ...number[]];
      selected_internal_level: number;
      metadata: RecommendedLevelMetadata;
    }
  | {
      requested_displayed_level: number;
      status: "out_of_range" | "unreachable";
      /**
       * @minItems 0
       * @maxItems 0
       */
      canonical_internal_levels: [];
      selected_internal_level: null;
      metadata: RecommendedLevelMetadata;
    };

export interface JobSnapshot {
  job_id: string;
  state: "queued" | "running" | "cancel_requested" | "completed" | "cancelled" | "failed";
  sequence: number;
  query_digest: string;
  context_digest: string;
  cursor: number;
  start_cursor: number;
  /**
   * @maxItems 100
   */
  candidates: {
    candidate_id: string;
    context_digest: string;
    seed: number;
    playthrough: number | null;
    rarity: number;
    record_stage: "final_record" | "native_stage_one" | "effect_sequence_only";
    installable: boolean;
    install_blocker: string | null;
    effects: {
      slot: number;
      effect_id: number;
      value: number;
      metadata: number;
      prefix: number;
      tail_0: number;
      tail_1: number;
      roll_percent: number | null;
    }[];
    auxiliary: {
      terrain: {
        value: number;
        display_effect_keys: number[];
      };
      enemy_groups: {
        lookup_key: number;
        role: number;
      }[][];
      special_rules: {
        key: number;
        raw_value: number | null;
        display_value: number | null;
        display_unit: string | null;
        display_grade: string | null;
        qualifier_kind: string | null;
        qualifier_key: number | null;
      }[];
    } | null;
    cursor: number | null;
    evidence: "certified_offline_replay" | "native_finalized_generation";
    installation_available: boolean;
    initial_challenge_capacity: number;
  }[];
  progress: {
    start_after_trial: number;
    inspected_through_trial: number;
    family_size: number;
    fixed_seed_count: number;
    stages: {
      kind: string;
      values: number[];
      count: number;
    }[];
    complete_match_count: number;
    exhausted_family: boolean;
  } | null;
  stop_reason: ("result_limit" | "budget_reached" | "family_exhausted" | "cancelled" | "error") | null;
  error: {
    code: string;
    message: string;
  } | null;
  resume_token: string | null;
  elapsed_ms: number;
}
export interface Handshake {
  protocol: 1;
  contract_digest: string;
  role: "offline_search";
  context: {
    product_version: string;
    game_profile: string;
    resources_digest: string;
    algorithm_version: string;
    policy_version: string;
    context_digest: string;
    seed_accelerator_abi: number | null;
    seed_accelerator_build_id: string | null;
  };
  capabilities: {
    playthroughs: number[];
    rarities: number[];
    cuda_pivot_and_auxiliary: boolean;
    directcompute_effect_filter: boolean;
    cpu_exact_replay: boolean;
    bulk_cpu_requires_opt_in: boolean;
    save_write: false;
    runtime_calls: false;
    cached_rarity5_playthroughs?: (4 | 5)[];
  };
}
export interface SearchCatalog {
  context_digest: string;
  ordinary_effects: {
    effect_id: number;
    name: string;
  }[];
  grace_effects: {
    effect_id: number;
    name: string;
  }[];
  terrain_options?: {
    option_id: string;
    name: string;
    effect_keys: number[];
    aggregate: boolean;
  }[];
  enemy_options?: {
    lookup_key: number;
    role: number;
    name: string;
  }[];
  special_rule_options?: {
    key: number;
    name: string;
    variant: {
      [k: string]: unknown;
    };
  }[];
  special_rule_families?: {
    name: string;
    keys: number[];
  }[];
  recommended_level: RecommendedLevelMetadata;
}
export interface RecommendedLevelMetadata {
  minimum_internal_level: number;
  maximum_internal_level: number;
  minimum_displayed_level: number;
  maximum_displayed_level: number;
  selection_policy: "lowest_canonical_internal_level";
  evidence: "captured_native_curve_prediction";
}
export interface CandidateTransfer {
  candidate_id: string;
  context_digest: string;
  level: number;
  seed: number;
  playthrough: number;
  rarity: 3 | 4 | 5;
  record_stage: "final_record" | "native_stage_one" | "effect_sequence_only";
  record_hex: string;
  installation_record_hex: string | null;
  /**
   * @minItems 1
   * @maxItems 7
   */
  effects:
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ]
    | [
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        },
        {
          slot: number;
          effect_id: number;
          value: number;
          metadata: number;
          prefix: number;
          tail_0: number;
          tail_1: number;
          roll_percent: number | null;
        }
      ];
}
export interface CacheReference {
  cache_id: string;
}
